
# 针对内置tomcat生效
server:
  port: 9092
  # 配置次路径后，所有的资源访问路径都会加上/backend 前缀
  servlet:
        context-path: /backend

spring:
     freemarker:
         cache: false
         request-context-attribute: request
         suffix: .ftl
         settings:
           number_format: 0.##

     redis:
       host: localhost
       port: 6379
       timeout: 10000ms
       database: 0
       lettuce:
         pool:
           max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
           max-wait: -1ms
           max-idle: 8 # 连接池中的最大空闲连接 默认 8
           min-idle: 0
         #spring.redis.password= # Login password of the redis server.
         #spring.redis.sentinel.master= # Name of Redis server.
         #spring.redis.sentinel.nodes= # Comma-separated list of host:port pairs.

# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别  error、warn、info、debug、trace、all
    root: warn
  # 在不指定路径，只指定输出日志的文件名，默认输出至当前项目下
  # 若指定，则会输出至指定目录下
  file: log/backend-web.log